Rework of ORM
cram2/pycram pull request #101
Opened 2023-09-28 10:20 UTC by davidprueser

reworking orm structure to automatically join information and shrink size of user queries.

2023-10-10 13:31 UTC, tomsch420 requested changes
Also try to set the __tablename__ attribute in the Base class

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/base.py
> +    description: Mapped[str] = mapped_column(init=False)
Why is this init=False?

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/base.py
> +    metadata_id: Mapped[Optional[int]] = mapped_column(ForeignKey("MetaData.id"), default=None)
Why are these declared here?

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/base.py
> +    orientation_table_entry: Mapped["Quaternion"] = relationship(init=False)
The actual object quaternion should be in the quaternion field. The foreign key should have a name like quaternion_fk or something consistent.

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/motion_designator.py
> +    object_table_entry: Mapped[ObjectDesignator] = relationship(init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/motion_designator.py
> +    position: Mapped[int] = mapped_column(ForeignKey("Position.id"), init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/motion_designator.py
> +    object_table_entry: Mapped[ObjectDesignator] = relationship(init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    robot_state_table_entry: Mapped[RobotState] = relationship(init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
>          "polymorphic_identity": __tablename__,
can polymorphic identities be declared in supertype via sqlalchemy property like the metadata id?

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    # def __init__(self, arm: str = None):
commented code block

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    position_table_entry: Mapped[Position] = relationship(init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    #     super().__init__()
commented code block

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    position: Mapped[Optional[float]] = mapped_column(default=None)
name is weird. This shoud be renamed to height

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    #     super(MoveTorsoAction, self).__init__()
commented 👏 code 👏 block 👏

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    #     self.gripper = gripper
commented 👏 code 👏 block 👏

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    object_table_entry: Mapped[ObjectDesignator] = relationship(init=False)
naming

2023-10-10 13:31 UTC, tomsch420 commented on src/pycram/orm/action_designator.py
> +    object_table_entry: Mapped[ObjectDesignator] = relationship(init=False)
n 👏 a 👏 m 👏 i 👏 n 👏 g 👏

2023-10-10 14:18 UTC, davidprueser commented on src/pycram/orm/task.py
> +    reason: Mapped[Optional[str]] = mapped_column(default=None)
What do you mean?

2023-11-16 09:34 UTC, tomsch420 approved these changes

2023-11-16 09:34 UTC, tomsch420 commented on src/pycram/designators/object_designator.py
> +            # if self.part_of:
delete commented code blocks

2023-11-17 11:32 UTC, tomsch420 approved these changes

2023-11-17 11:52 UTC, merged