Abstract world
cram2/pycram pull request #133
Opened 2024-01-24 11:13 UTC by AbdelrhmanBassiouny

Abstracting the world class from pybullet to have a flexible simulator backend for pycram

2024-01-24 15:26 UTC, tomsch420 requested changes
Check the tutorials for intro and giskard if this is how it should be.

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +    def update_link_transforms(self, transform_time: Optional[rospy.Time] = None):
DOC

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +def _get_robot_name_from_urdf(urdf_string: str) -> str:
remove it

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +        self.parent_link = parent_link
typing

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +        self._loose = False and not bidirectional
loose should be be "not bidirectional"

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +        Creates an attachment between the parent object and the child object.
no doc for the parameter

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +    def update_transform_and_constraint(self):
DOC!!!!!111!

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +        attachment.loose = False if self.loose else True
change to "not self.loose"

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world.py
> +def _world_and_id(world: World) -> Tuple[World, int]:
remove

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_dataclasses.py
> +    A: float = 1
doc A :tomato:

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_dataclasses.py
> +    joint_frame_position_wrt_parent_origin: List[float]
Use a Transform here

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_dataclasses.py
> +class Point:
Use Point message, look at pose for example

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_dataclasses.py
> +    link_inertial_frame_positions: List[List[float]]
Use Pose

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_reasoning.py
> +class ReasoningError(Exception):
move to pan_failures

2024-01-24 15:26 UTC, tomsch420 commented on src/pycram/world_reasoning.py
> +def get_visible_objects(
doc ...

2024-01-25 13:30 UTC, tomsch420 requested changes
Furthermore check for code coverage.

2024-01-25 13:30 UTC, tomsch420 commented on src/pycram/pose.py
> +    @classmethod
use rospy timestamp

2024-01-25 13:30 UTC, tomsch420 commented on src/pycram/process_modules/boxy_process_modules.py
> +def _transform_to_torso(pose_and_rotation: Tuple[List[float], List[float]], robot: BulletWorldObject) -> Tuple[
delete this method

2024-01-25 13:47 UTC, tomsch420 requested changes
Testing PR view in pycharm

2024-02-01 11:13 UTC, AbdelrhmanBassiouny commented on src/pycram/world.py
> +        return self.pose.to_transform(self.tf_frame)
it does not but there is a stamp in the header of the pose that can be used.

2024-02-20 14:22 UTC, tomsch420 commented on src/pycram/world.py
> -            time.sleep(20 * World.simulation_time_step)
make this 20 a constant somewhere

2024-02-20 14:23 UTC, tomsch420 commented on src/pycram/world_constraints.py
> +                 parent_link: 'Link',
annotations

2024-02-20 14:24 UTC, tomsch420 commented on src/pycram/world_object.py
> +from pycram.enums import ObjectType, JointType
absolute imports

2024-04-08 10:31 UTC, closed without merging

2024-04-08 10:31 UTC, Tigul commented
With [85eddde](https://github.com/cram2/pycram/commit/85eddde1cb76bf9fa1652f7a7ca493754e666742) this PR is merged. I don't know why GitHub does not recognize it but I will close this PR with this comment.