[resources]: Added additional resources
cram2/pycram pull request #148
Opened 2024-04-22 12:43 UTC by K3cks

Added additional models for objects, robots and worlds.
Restructured objects, robots and worlds into seperate directories. 
Adjusted default paths for robots and search for resources in all subdirectories.
In 'models' is the very first version of the probablistic model from @tomsch420

2024-04-22 13:14 UTC, sunava commented
Please fix tests aswell.

2024-04-22 13:27 UTC, tomsch420 requested changes
I am very sure that all resource files should not be tracked in git. Talk to @Tigul  about his vision for that.

2024-04-22 13:27 UTC, tomsch420 commented on resources/models/defenitly_not_hard_coded.pm
Please do not commit models to git. This model is small and hence wont blow up, however it is not the intended functionality. Use some MLOps stack like MLFLow that is set up in the institute for specifically that purpose.

2024-04-22 13:33 UTC, sunava commented on resources/models/defenitly_not_hard_coded.pm
Mhm, I was thinking that in the future, we could have models like yours to answer questions like, "where might I find the spoon?" In my demos (which haven't been pushed yet because I'm focused on finalizing the functionality), I'm already using that model. I thought this could be the first step toward using your model, because the calls remain the same; only your answers would change as your model gets more trained.

2024-04-22 13:36 UTC, sunava commented on resources/models/defenitly_not_hard_coded.pm
oh i see, that was the wrong model nvm thanks for noticing

2024-04-22 15:00 UTC, sunava approved these changes

2024-04-22 15:03 UTC, sunava commented
waiting for the meeting tmr to approve this. but looks good

2024-04-23 10:33 UTC, Tigul commented
Maybe we could make a seperate Repo and use it as a submodule for the meshes.

2024-04-23 15:24 UTC, sunava commented
will rework this based on the discussion today

2024-04-23 18:44 UTC, closed without merging