Refactor 2024
cram2/pycram pull request #155
Opened 2024-04-24 12:10 UTC by Tigul

Big refactor of PyCRAM which moves files around
Changes are:
    * Removed UR5 Meshes
    * Made folder for robot URDFs
    * unified utils.py and helper.py, also moved methods from helper.py to pose.py
    * task.py was renamed to tasktree.py
    * world.py was moved to datastructures
    * resolver package was renamed to specialized_designators and moved to designators package
    * designators/actions was renamed to designatos/performables
    * The cache manager now searches the datadirectory recursively for a matching file
    * Names of WorldObjects are now unique, spawning a second object with the same name will lead to an error message 
    * The Tf_frame of WorldObjects does not contain the id anymore.

2024-05-13 09:54 UTC, sunava commented
This branch has conflicts that must be resolved

2024-05-27 10:43 UTC, sunava commented
@Tigul this has even more merge conflicts now since I approved your giskard pr

2024-05-27 10:43 UTC, sunava requested changes

2024-05-28 12:15 UTC, Tigul commented on src/pycram/datastructures/pose.py
> +    def multiply_quaternions(self, quaternion: List) -> None:
Yes because the orientation of the Pose is changed

2024-05-28 13:43 UTC, merged