OntologyManager: add reason() + test
cram2/pycram pull request #166
Opened 2024-06-10 15:17 UTC by Tadinu

Following #141, this PRs add reasoning APIs to `OntologyManager`, specifically to allow dynamic SWRL rules to be created for instances of an ontology concept class.
* Add `reason()`: reason on ontology concepts and their relations of a specific ontology world. Calling this will generate deducted facts that are updated to contents of property instances.
* Basic rules of binary relation (reflexivity, symmetry, transitivity) are introduced. NOTE: These just act as basic examples of rule definitions and more emphasize on the dynamic creation aspect. Same effects could be also achieved but incur creating new property classes, subclassing `ReflexiveProperty, SymmetricProperty, TransitiveProperty`
* Fix a bug causing reasoning to fail, due to missing required specific world as domain of ontology concepts for reasoning.
-> `LoadOntology()` now by default load from an IRI to the owlready2-provided `default_world`, which is also by default used for 
`sync_reasoner_pellet()/sync_reasoner_hermit()`.
-> Alternatively, `create_ontology_world()` is added in case of loading ontologies into a custom persistent world & reasoning on it specifically.
* `test_ontology.py`: Add `test_reasoning()`, also do post-cleaning up of `owl/sql, sql-journal` files generated during the test.
* `create_ontology_concept_class()/create_ontology_property_class()`: add optional `ontology` param to allow creating them into a specific ontology namespace, aside from the default `main_ontology`.
* `create_ontology_triple_classes()`:
  + (1) `predicate_name -> predicate_class_name`, `inverse_predicate_name -> inverse_predicate_class_name` for clarity
  + (2) add `predicate_python_attribute_name, inverse_predicate_python_attribute_name`, by default taking values from (1) if not  explicitly specified, for consistency
  + Make `ontology_object_parent_class` type hint as `Thing | object` to support such an `owlready2.FunctionalProperty` relation between `owlready2.Thing` and pure python types

2024-06-11 13:50 UTC, Tadinu commented
test_ontology_reasoning() currently fails due to JRE, which is required by owlready2 reasoner, is not available atm

2024-06-11 13:50 UTC, Tadinu commented
test_ontology_reasoning() currently fails since JRE, which is required by owlready2 reasoner, is not available atm

2024-07-09 09:39 UTC, Tigul requested changes
Please change

2024-07-09 09:39 UTC, Tigul commented on test/test_ontology.py
> +        if not owlready2:
There is a @skipif that should be used in this case

2024-07-09 09:39 UTC, Tigul commented on test/test_ontology.py
> +        if not owlready2:
@skipif

2024-07-09 09:39 UTC, Tigul commented on test/test_ontology.py
> +        if not owlready2:
@skipif

2024-07-09 09:39 UTC, Tigul commented on test/test_ontology.py
> +        if not owlready2:
@skipif

2024-07-09 09:39 UTC, Tigul commented on src/pycram/ontology/ontology.py
> +    def load_ontology(self, ontology_iri: str) -> tuple[Optional[Ontology], Optional[Namespace]]:
From what I can see the return should be Optional[Tuple[Ontology, Namespace]]

2024-07-25 12:12 UTC, Tigul approved these changes

2024-07-25 12:12 UTC, merged