New robot description
cram2/pycram pull request #170
Opened 2024-07-02 11:22 UTC by Tigul

This PR adds a refactor of the Robot description to better structure the description and remove some redundancy

2024-07-09 09:58 UTC, tomsch420 requested changes

2024-07-09 09:58 UTC, tomsch420 commented on doc/source/new_robot.rst
> +Adding a new robot to PyCRAM
isnt this a new **type** of robot?

2024-07-09 09:58 UTC, tomsch420 commented on doc/source/new_robot.rst
> +process modules in pycram.process_modules.
this can be a clickable link using a ref to the autoapi doc.
Should be like {py:class}`pycram.process_modules`

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/costmaps.py
> +    #     for i in range(0, map.shape[0]):
for keeping track of old code we got version control. Blocks of commented code is a code smell.

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/external_interfaces/ik.py
> +    arm = "left" if (gripper_name == RobotDescription.current_robot_description.kinematic_chains["left"].get_tool_frame()) else "right"
is the string access here intended?

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/object_descriptors/urdf.py
> +            with suppress_stdout_stderr():
please add a comment here why supression is needed

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/process_modules/boxy_process_modules.py
>      if arm == "left":
intended string comparison?

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/robot_descriptions/__init__.py
very nice migration strategy

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/world_concepts/world_object.py
> +        #     if self.description.name == robot_description.name:
:nose:

2024-07-09 09:58 UTC, tomsch420 commented on test/README.md
why is this a readme in the test and not a chapter in the doc?

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/robot_description.py
> +        self.torso_joint = torso_joint
Shouldn't the class member be define outside of the init and the doc and types also there?

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/robot_description.py
> +        with suppress_stdout_stderr():
document why?

2024-07-09 09:58 UTC, tomsch420 commented on src/pycram/robot_description.py
> +        self.torso_joint = torso_joint
for all classes in this document

2024-07-10 08:24 UTC, Tigul commented on doc/source/new_robot.rst
> +Adding a new robot to PyCRAM
Nope, it's a new robot platform

2024-07-10 11:51 UTC, merged