[SemanticCostmap] applied margin
cram2/pycram pull request #180
Opened 2024-08-13 10:24 UTC by sunava

I use this Costmap to generate placement poses for my complete pick-and-place demo on the real robot. The outer edges are reduced because the robot requires some clearance, especially when dealing with structures like shelves where the outer areas might be restricted. Since the standard semantic costmap is no longer in use, perhaps we should consider renaming this to something like placeSemanticCostmap, @Tigul. In the attached image, you can see an example for a countertop. Please note that I work with TF frames oriented according to the direction we agreed upon within the Suturo project.
![Screenshot from 2024-08-13 12-17-33](https://github.com/user-attachments/assets/e5746151-bf7c-409b-9f6e-eb8d7117b707)

2024-08-13 10:24 UTC, sunava commented
for example uses:
 sem = SemanticCostmap(apartment_desig.resolve().world_object, "island_countertop")

sem.visualize()

```

2024-08-15 15:06 UTC, Tigul commented on src/pycram/costmaps.py
> +        # Trim the left and right sides, only keep points before the 0s
Why trim here when the margin is already applied above?

2024-08-19 08:44 UTC, tomsch420 requested changes

2024-08-19 08:44 UTC, tomsch420 commented on src/pycram/costmaps.py
> +    def __init__(self, object, urdf_link_name, size=100, resolution=0.02, world=None, margin_cm=0.2):
Something like margin_cm should just be margin: Unit. This way people can write whatever unit they want there. Consider using some metric package here like https://github.com/hgrecco/pint

2024-09-02 12:27 UTC, Tigul commented
Since there will be another implementation soon I will close this

2024-09-02 12:27 UTC, closed without merging