Added turtlebot3 (waffle_pi)
cram2/pycram pull request #186
Opened 2024-08-19 09:31 UTC by K3cks

Added resource files to launch the turtlebot3 (model: waffle_pi).
Also adjusted launch file to include turtlebot3 as option.

2024-08-19 10:01 UTC, sunava requested changes

2024-08-19 10:01 UTC, sunava commented on src/pycram/robot_descriptions/turtlebot3_waffle_pi_description.py
> +filename = rospack.get_path('pycram') + '/resources/robots/' + "turtlebot3_waffle_pi" + '.urdf'
Can we maybe rename the robot to just turtle bot and have in the description that turtle bot == turtlebot3_waffle_pi cause i don't wanna write this all the time when using the robot

2024-08-20 07:33 UTC, tomsch420 requested changes

2024-08-20 07:33 UTC, tomsch420 commented on src/pycram/robot_descriptions/turtlebot3_waffle_pi_description.py
> +rdm.register_description(turtlebot3_waffle_pi)
please provide a testcase if the turtlebot can be loaded like this.

2024-08-21 11:56 UTC, sunava approved these changes

2024-08-21 11:56 UTC, merged