Ontology to pycram objects
cram2/pycram pull request #191
Opened 2024-08-23 14:34 UTC by mpomarlan

Work in progress, but started a pull request to draw attention to this.

TODOs:

1. SERIOUS: get SOMA_DFL and/or SOMA_DFL_module online so the onto loader can get to them without needing to depend on the dfl python package. Currently, these would be accessible only on a github tree.
2. Serious: test to remove silly typos
3. Good to have (but not threatening to functionality, at least in limited use cases): Integration with rest of onto manager. E.g., I prefer to have an iri2Concept map to switch between string names and the actual OWLReady2 generated classes. What other functions in the onto manager may impact this mapping?
4. Good to have (eventually): query complex concept expressions. This will require integrating a different reasoner in there (Konclude) or only use modules of SOMA_DFL so that OWLReady2's HermiT doesn't die.
5. Good to have (eventually): a more elegant map between pycram object types and ontology classes.

2024-09-03 07:14 UTC, tomsch420 requested changes

2024-09-03 07:14 UTC, tomsch420 commented on src/pycram/ontology/ontology.py
> +
Please also provide tests for such methods. Furthermore stick to the RST docstrings.

2024-09-06 10:59 UTC, tomsch420 requested changes

2024-09-06 10:59 UTC, tomsch420 commented on src/pycram/ontology/ontology.py
> +        :type conceptName: str
types are not needed since they are annotated in the method signature

2024-09-06 10:59 UTC, tomsch420 commented on test/test_ontology.py
> +    @unittest.skipUnless(True, 'never skip')
this line does nothing. Remove it

2024-09-06 10:59 UTC, tomsch420 commented on test/test_ontology.py
> +    @unittest.skipUnless(True, 'Never skip')
remove

2024-09-06 16:07 UTC, Tadinu commented on test/test_ontology.py
> +                self.ontology_manager.main_ontology_iri is SOMA_DFL_ONTOLOGY_IRI:
```suggestion
                self.ontology_manager.main_ontology_iri is SOMA_HOME_ONTOLOGY_IRI or \
                self.ontology_manager.main_ontology_iri is SOMA_DFL_ONTOLOGY_IRI:
```

2024-09-06 16:12 UTC, Tadinu reviewed
This test is meant for any SOMA onto actually

2024-09-17 06:58 UTC, tomsch420 approved these changes

2024-11-07 10:57 UTC, closed without merging

2024-11-07 10:57 UTC, tomsch420 commented
Closing this due to inactivity