Integrating Gymnasium into Pycram
cram2/pycram pull request #222
Opened 2024-11-21 15:03 UTC by mkhoshnam

This pull request introduces the integration of the gymnasium_interface module into Pycram. The following changes have been made:

**Starting gymnasium_interface module:**

-         Implemented a dynamic PyCRAMGymEnv environment for training and testing Reinforcement learning agents.
-         Considered user-defined actions and reward functions for better flexibility.
-         Includes a task_executor module to handle various Pycram actions (Still on going).

**Key Features:**

-         Dynamically adjustable action space based on the user's configuration.
-         User-defined reward functions for scenario-specific tasks.

**New Files:**

-         src/gymnasium_interface/Pycram_gym_env.py: Contains the main gymnasium environment.
-         src/gymnasium_interface/task_executor.py: Includes logic for executing actions within the environment.
-         src/gymnasium_interface/example.py: Demonstrates how to use the gymnasium_interface.

Soon I will prepare a Read me file to describe how to use the environment

2024-11-22 09:45 UTC, tomsch420 requested changes

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
stick to naming conventions of files

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
> +class PyCRAMGymEnv(gym.Env):
class docstring missing

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
> +        Args:
we use RST formatting for docstrings, stick to it!

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
> +            actions (list): List of valid action names (e.g., ["navigate", "pick_up", "place"]).
why are the actions strings and not functions or classes?

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
> +            # Execute the action
you dont have to to obvious comments

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/Pycram_gym_env.py
> +        """Executes a step in the environment."""
arent the docstrings here inherited from the Gym?

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/__init__.py
> +__all__ = ["PyCRAMGymEnv", "PyCRAMTaskExecutor"]
dont do that

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/example.py
> +objects = [{"name": "milk", "type": "object", "urdf": "milk.stl", "pose": Pose([2.5, 2.10, 1.02])}]
super weird way of writing objects

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +class PyCRAMTaskExecutor:
class documentation

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        """Initializes task executor for PyCRAM actions."""
if your docstring is not adding any information you should not write it

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        print("Clearing all objects from BulletWorld...")
use logging instead of printing

2024-11-22 09:45 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
for the creation of classes from parameter dicts coordinate with jonas, he has written some cooler way

2024-11-22 09:52 UTC, Tigul requested changes

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
Filenames should be lowercase

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +from pycram.process_module import simulated_robot
Make this a relative import. "from ..process_module import simulated_robot"

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +            actions (list): List of valid action names (e.g., ["navigate", "pick_up", "place"]).
Please stick to the rst style doc strings, look at the other methods and classes for reference

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +        """Resets the environment."""
Add return to the doc string as well as the type hint for the returned value

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +        with simulated_robot:
That should only be set on the top level by the user

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +    def step(self, action, params=None):
Please add type hints to the parameter as well as the parameter doc to the doc string.

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/Pycram_gym_env.py
> +        """Fetches the current state of the environment."""
return in doc

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/example.py
The example should not be under the src folder, please move this to demos.

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +from pycram.worlds.bullet_world import BulletWorld
Relative imports

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +        self.world = BulletWorld(WorldMode.GUI)
Creating a new BulletWorld here will break everything. Use the existing world from "datastructures.World.current_world"

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +        print("Clearing all objects from BulletWorld...")
use the log functions from ros.logging instead of prints

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +    def clear_world(self):
There should be a method in the World class for this, if not please move this there.

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +        self.robot = Object("pr2", ObjectType.ROBOT, "pr2.urdf", pose=Pose([1.2, 1, 0]))
Would be cooler to make this dependend on the robot that was used before instead of always using the Pr2

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +    def reset_task(self, objects):
Type hints and doc string

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +            print(f"Adding object: {name}, URDF path: {urdf}, Pose: {pose}")
log functios from pycram.ros.logging instead of print

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +        with simulated_robot:
Please remove the simulated_robot since this should be set on the top level

2024-11-22 09:52 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +    def _navigate(self, params):
Type hints and some doc for all methods below

2024-11-22 09:52 UTC, Tigul commented on src/pycram/cache_manager.py
> +                                     mesh_transform: Optional['Transform'] = None) -> str:
When you import "from __future__ import annotations" you can use Transform directly without the quotation marks

2024-11-22 09:52 UTC, Tigul commented on src/pycram/costmaps.py
> +            return self.link.get_bounding_box()
This return is ambiguous since the bounding box might not be axis aligned

2024-11-22 09:52 UTC, Tigul commented on src/pycram/datastructures/dataclasses.py
> +    def get_transformed_box(self, transform: Transform) -> 'AxisAlignedBoundingBox':
Use __future__.annotations to use AxisAlignedBoundingBox directly

2024-11-26 12:24 UTC, tomsch420 requested changes
Please rewrite the git history to exclude your devel folder and push again otherwise this is not reviewable.

2024-11-26 14:32 UTC, closed without merging