Gymnasium interface changes
cram2/pycram pull request #228
Opened 2024-11-26 15:11 UTC by mkhoshnam

This pull request introduces the gymnasium_interface module, which includes the following files:

**-     example.py: An example file for using the Gymnasium interface.
-     pycram_gym_env.py: The implementation of the environment interface for Gymnasium.
-     task_executor.py: A script for executing tasks within the Gymnasium environment.**

These files are added as part of integrating the Gymnasium interface into the existing PyCRAM system. The new module will allow interaction with Gym environments, enabling reinforcement learning and other task execution capabilities.

Additionally, I have ensured that only the necessary files related to the Gymnasium interface have been pushed, without including the entire dev branch.

2024-11-26 15:26 UTC, tomsch420 requested changes

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/example.py
> +objects = [
this needs some more engineering. Perhaps objects that do not have worlds yet? Please prepare a short discussion of this kind of problem for the next pycram meeting

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/example.py
> +    "navigate": {"target_pose": Pose(position=[1.0, 2.0, 0.0], orientation=[0.0, 0.0, 0.0, 1.0])},
these should be function points in my opinion and not key-value stores

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/pycram_gym_env.py
> +    def __init__(self, actions, default_params=None, objects=None, reward_function=None):
use function points instead, talk with @Leusmann  how to do so

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/pycram_gym_env.py
> +    :type actions: list
annotate types in the constructor, not in the docstring.

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/pycram_gym_env.py
> +        :return: The initial state of the environment.
this docstring should be inherited from the super class

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/pycram_gym_env.py
> +        :param action: The action index to execute.
this docstring should be inherited from the super class

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        world (BulletWorld): The BulletWorld instance managing the environment.
please annotate them as class variables

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        Initializes the task executor for PyCRAM actions.
useless docstring

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        :type action: str
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        Navigates the robot to a target location.
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        Picks up an object.
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        :param params: Parameters for the close action, including "handle_desig" and "arm".
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
> +        :type objects: list[dict]
types :clap: in :clap:  the :clap: signature :clap:

2024-11-26 15:26 UTC, tomsch420 commented on src/gymnasium_interface/task_executor.py
Generally the structure here is very repetitive with pycram designators, this should not be

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/__init__.py
> +from gymnasium_interface.pycram_gym_env import PyCRAMGymEnv
Make this relative imports

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/example.py
> +from gymnasium_interface.pycram_gym_env import PyCRAMGymEnv
Make these relative imports

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/example.py
> +logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
Use the logging from pycram.ros.logging instead of the Python logging

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +    Attributes:
Use rst syntax for the doc string

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +from pycram.world_concepts.world_object import Object
relative imports

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
Use logging from pycram.ros.logging

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +        self.apartment = Object("apartment", "environment", "apartment.urdf")
Use ObjectType.ENVIRONMENT instead of the string

2024-11-28 09:31 UTC, Tigul commented on src/gymnasium_interface/task_executor.py
> +    def _navigate(self, params: Dict[str, Pose]) -> None:
Why don't you execute the action directly?

2025-02-05 11:37 UTC, tomsch420 commented
Nothing happened here so I close it.

2025-02-05 11:37 UTC, closed without merging