Adds some utility function usable to merge two databases together - Nils
cram2/pycram pull request #98
Opened 2023-09-20 11:19 UTC by Leusmann

2023-09-20 11:20 UTC, tomsch420 commented
Write a better name and description

2023-09-20 11:31 UTC, tomsch420 requested changes

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +def logDB(in_session, filename, b_write_to_console=False):
no abbreviations in variables, functions, etc..
Also no camel case for function names and variables.

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +def logDB(in_session, filename, b_write_to_console=False):
Also type hint the parameters and return values

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +        """
wrong indent

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    f = open(filename, "w")
with open(f, "w") as f:
instead of manual opening and closing

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                print("I am writing: {}".format(str(column_object.__dict__)))
rospy.log

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +        Prints all ORM Class data within the given Session.
wrong indent

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    '''
double quotes instead of single quotes in comment strings.

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +def update_primary_key(source_engine, destination_engine):
type hints

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    Will create own session
Write a _coherent and consistent_ text in imperative form.

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                highest_free_keyValue = max(all_memory_key_values)[0] + 1  # ToDo: Make it even more generic? # We will add 1 to the id then let the DB to the rest, afterwards we will compy all info
80 digits limit for lines

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +        highest_free_keyValue = 0
snake_case

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +        primaryKeys[table] = {}
snake_case

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                highest_free_keyValue = max(all_memory_key_values)[0] + 1  # ToDo: Make it even more generic? # We will add 1 to the id then let the DB to the rest, afterwards we will compy all info
snake_case

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                    print("Found primarykey collision in table {} value: {} max value in memory {}".format(table,
rospy.log

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    '''
double qoutes and type hints

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    Primary keys of destination will be updated so that there are no collisions when merging.
writing style

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                        print("WARNING: Ignored already detached ORM Object {} ".format(
rospy.warn

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                            row[key]))  # ToDo: Maybe give option to include theses items (could break something)
fix todo

2023-09-20 11:31 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                            row[key]))  # ToDo: Maybe give option to include theses items (could break something)
Use Notes syntax for docstring to address these issues

2023-09-20 11:32 UTC, tomsch420 commented
Also create test cases

2023-09-21 07:42 UTC, Leusmann commented
Should be fixed with the newest commits. Please check again.

2023-09-21 12:11 UTC, tomsch420 requested changes

2023-09-21 12:11 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    note:
brah

2023-09-21 12:11 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    memory databases as there are no triggers
as of version x.x

2023-09-21 12:11 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +    :param filename: (String) Filename of the logfile
duplicated information

2023-09-21 12:11 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +def write_database_to_file(in_session: sqlalchemy.orm.session, filename: str, b_write_to_console: bool = False):
This hints a module and not the Session class

2023-09-21 12:18 UTC, Leusmann commented
I would put the testcases in another merge request but it is up to you

2023-09-21 12:19 UTC, tomsch420 commented
No merge without testing

2023-11-07 08:48 UTC, tomsch420 requested changes

2023-11-07 08:48 UTC, tomsch420 commented on test/test_database_merger.py
> +from anytree import Node,RenderTree,LevelOrderIter
ctrl+alt+shift+L

2023-11-07 08:48 UTC, tomsch420 commented on test/test_database_merger.py
> +    @unittest.skipIf(not (pathlib.Path("test_database_merger.json").resolve().is_file()),
make the configuration a class.

2023-11-07 08:48 UTC, tomsch420 commented on test/test_database_merger.py
> +        pycram.orm.utils.print_database(self.source_session_maker)
assert what?

2023-11-07 08:48 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +def update_primary_key(source_session_maker: sqlalchemy.orm.sessionmaker,
functions should do one thing. This function can be partitioned in a lot more functions

2023-11-07 08:48 UTC, tomsch420 commented on src/pycram/orm/utils.py
> +                    "SELECT con.oid, con.conname, con.contype, con.confupdtype, con.confdeltype, con.confmatchtype, pg_get_constraintdef(con.oid) FROM pg_catalog.pg_constraint con INNER JOIN pg_catal
replace with sqlalchemy queries.

2023-12-01 13:51 UTC, Leusmann commented
Did some update here. Please check again.

2023-12-12 13:41 UTC, tomsch420 commented on examples/migrate_neems.ipynb
> +    "i=0\n",
that cell seems unnescessary

2023-12-12 13:41 UTC, tomsch420 commented on examples/migrate_neems.ipynb
> +}
show the cool output of the merged database

2023-12-19 12:20 UTC, tomsch420 approved these changes

2024-01-03 21:51 UTC, merged